"""Safe user-level systemd service rendering and lifecycle management."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
from collections.abc import Callable, Mapping, Sequence
from dataclasses import asdict, dataclass
from pathlib import Path

GENERATED_MARKER = "# Generated by mi-remote service install\n"
SERVICE_NAME = "mi-remote.service"
UDEV_RULES = """# Grant the active desktop session access only to Xiaomi RC003 input event nodes.
SUBSYSTEM=="input", KERNEL=="event*", ATTRS{idVendor}=="2717", ATTRS{idProduct}=="32b8", TAG+="uaccess"
# Shared input nodes need a filtered virtual device to forward every key except F5/F9.
KERNEL=="uinput", GROUP="input", MODE="0660", OPTIONS+="static_node=uinput"
"""


class ServiceError(RuntimeError):
    pass


@dataclass(frozen=True)
class ServiceResult:
    action: str
    applied: bool
    changed: bool
    path: Path
    unit: str = ""


@dataclass(frozen=True)
class ServiceStatus:
    path: Path
    installed: bool
    managed: bool
    enabled: str
    active: str

    def to_json(self) -> str:
        data = asdict(self)
        data["path"] = str(self.path)
        return json.dumps(data, ensure_ascii=False, indent=2)


def render_service_status(status: ServiceStatus) -> str:
    return "\n".join(
        (
            f"服务文件：{status.path}",
            f"已安装：{'是' if status.installed else '否'}",
            f"由 MiRemote 管理：{'是' if status.managed else '否'}",
            f"开机启用：{status.enabled}",
            f"当前状态：{status.active}",
        )
    )


class ServiceManager:
    def __init__(
        self,
        *,
        executable: str | Path | None = None,
        config_home: str | Path | None = None,
        environment: Mapping[str, str] | None = None,
        command_runner: Callable[[Sequence[str]], object] | None = None,
    ):
        self.environment = dict(os.environ if environment is None else environment)
        resolved = executable or shutil.which("mi-remote")
        if not resolved:
            raise ServiceError("无法确定 mi-remote 可执行文件路径")
        self.executable = str(Path(resolved).expanduser().resolve())
        if config_home is None:
            config_home = self.environment.get("XDG_CONFIG_HOME", Path.home() / ".config")
        self.config_home = Path(config_home).expanduser()
        self.service_path = self.config_home / "systemd/user" / SERVICE_NAME
        self.command_runner = command_runner or self._run_command

    def render(
        self,
        *,
        voice_only: bool = False,
        address: str | None = None,
        inject: bool = True,
    ) -> str:
        arguments = [self.executable, "voice", "--engine", "auto"]
        if not voice_only:
            arguments.append("--config")
        if inject:
            arguments.append("--inject")
        if address:
            arguments.extend(("--address", address))
        exec_start = " ".join(self._quote_systemd(value) for value in arguments)
        return (
            GENERATED_MARKER
            + "[Unit]\n"
            + "Description=MiRemote RC003 voice input and key mapping\n"
            + "After=graphical-session.target bluetooth.target\n"
            + "PartOf=graphical-session.target\n\n"
            + "[Service]\n"
            + "Type=simple\n"
            + f"ExecStart={exec_start}\n"
            + "Restart=on-failure\n"
            + "RestartSec=3\n"
            + "TimeoutStopSec=20\n\n"
            + "[Install]\n"
            + "WantedBy=graphical-session.target\n"
        )

    def install(
        self,
        *,
        apply: bool = False,
        force: bool = False,
        start: bool = True,
        voice_only: bool = False,
        address: str | None = None,
        inject: bool = True,
    ) -> ServiceResult:
        unit = self.render(voice_only=voice_only, address=address, inject=inject)
        if not apply:
            return ServiceResult("install", False, False, self.service_path, unit)
        if self.service_path.exists():
            existing = self.service_path.read_text(encoding="utf-8")
            if existing == unit:
                changed = False
            elif not force:
                raise ServiceError(f"服务文件已存在：{self.service_path}；使用 --force 才允许覆盖")
            else:
                self._atomic_write(unit)
                changed = True
        else:
            self._atomic_write(unit)
            changed = True
        self._systemctl("daemon-reload")
        if start:
            self._systemctl("enable", "--now", SERVICE_NAME)
        return ServiceResult("install", True, changed, self.service_path, unit)

    def uninstall(self, *, apply: bool = False, force: bool = False) -> ServiceResult:
        if not apply:
            return ServiceResult("uninstall", False, False, self.service_path)
        changed = False
        if self.service_path.exists():
            existing = self.service_path.read_text(encoding="utf-8")
            if not existing.startswith(GENERATED_MARKER) and not force:
                raise ServiceError(
                    f"拒绝删除非 MiRemote 生成的服务：{self.service_path}；需要 --force"
                )
            self._systemctl("disable", "--now", SERVICE_NAME, allow_failure=True)
            self.service_path.unlink()
            changed = True
            self._systemctl("daemon-reload")
        return ServiceResult("uninstall", True, changed, self.service_path)

    def status(self) -> ServiceStatus:
        installed = self.service_path.is_file()
        managed = installed and self.service_path.read_text(encoding="utf-8").startswith(
            GENERATED_MARKER
        )
        enabled = self._query_systemctl("is-enabled") if installed else "not-installed"
        active = self._query_systemctl("is-active") if installed else "inactive"
        return ServiceStatus(self.service_path, installed, managed, enabled, active)

    def _atomic_write(self, text: str) -> None:
        self.service_path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
        temporary = None
        try:
            with tempfile.NamedTemporaryFile(
                "w",
                encoding="utf-8",
                dir=self.service_path.parent,
                prefix=f".{SERVICE_NAME}.",
                delete=False,
            ) as handle:
                temporary = Path(handle.name)
                handle.write(text)
                handle.flush()
                os.fsync(handle.fileno())
            temporary.chmod(0o644)
            os.replace(temporary, self.service_path)
        finally:
            if temporary and temporary.exists():
                temporary.unlink()

    def _systemctl(self, *arguments: str, allow_failure: bool = False) -> object:
        result = self.command_runner(("systemctl", "--user", *arguments))
        if getattr(result, "returncode", 1) and not allow_failure:
            detail = str(getattr(result, "stderr", "")).strip()
            raise ServiceError(f"systemctl {' '.join(arguments)} 失败：{detail or '未知错误'}")
        return result

    def _query_systemctl(self, verb: str) -> str:
        result = self._systemctl(verb, SERVICE_NAME, allow_failure=True)
        output = str(getattr(result, "stdout", "")).strip()
        return output or ("unknown" if getattr(result, "returncode", 1) else "ok")

    @staticmethod
    def _quote_systemd(value: str) -> str:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("%", "%%")
        return f'"{escaped}"'

    def _run_command(self, arguments: Sequence[str]) -> subprocess.CompletedProcess[str]:
        try:
            return subprocess.run(
                arguments,
                check=False,
                capture_output=True,
                text=True,
                env=self.environment,
            )
        except OSError as exc:
            raise ServiceError(f"无法运行 {arguments[0]}：{exc}") from exc
